spring.application.name=media-hub-spring
spring.datasource.url=${MEDIAHUB_DB_URL}
spring.datasource.username=${MEDIAHUB_DB_USERNAME}
spring.datasource.password=${MEDIAHUB_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_PASSWORD}
app.admin-bootstrap.enabled=true
app.admin-bootstrap.email=${MEDIAHUB_ADMIN_EMAIL:}
app.admin-bootstrap.password=${MEDIAHUB_ADMIN_PASSWORD:}
jwt.expiration=86400000
tmdb.api.key=${TMDB_API_KEY}
omdb.api.key=${OMDB_API_KEY}
